CREATE TABLE `usuarios` (
  `ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USUARIO` varchar(20) NOT NULL,
  `CORREO` varchar(30) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
